### PR TITLE
Fix tutorials light theme

### PR DESCRIPTION
**Pull request by louis-md**

### CODE REVIEW

**Comment by tanay1337** [comment]
@louis-md there seems to be a build error in this PR. Can you please resolve it?

**Review by tanay1337 — CHANGES_REQUESTED** [review]
@louis-md there seems to be a build error in this PR. Can you please resolve it?

**Review by valle-xyz — CHANGES_REQUESTED** [review]
Hey,

I went through all tutorials. Here are some points that should be addressed.

**Passkeys React Tutorial:**
* The text about adding the stylesheets is irritating. It should say that the file should be replaced (and contain the complete code of the file, which it does). 
* ./components/SafeAccountDetails.tsx:18:1 imports SafeLogo.png, which does not exist. 
* The light mode does not really work. The icons in the top bar are not visible. I recommend removing all dark/light mode related variables and only use values that display a dark mode. Also on Chrome the background is white, even when dark mode is turned on.
* We should add a hint, that the app only works in Chrome, not in Firefox (Firefox still has the bug with passkeys).

**Passkey Vue:**
* remove the unused links variable from the default layout
* The terminal command in the components section failes, as it tries to `cd` into the `components` directury instead of creating it.
* The Safe Link and Jiffyscan Link do not work (I think the variables should be reactive)
* Light mode works (!), it does not look the best as some buttons have low contrasting colors, but it works.
* On Chrome, only light mode works, so even when the browser is set to dark mode, the app displays light mode.
* We should add a hint, that the app only works in Chrome, not in Firefox (Firefox still has the bug with passkeys).

**7579 tutorial:**
* is not functional, as multiple files are not created. 
* I did not check the functionality of the app, as I currently rework this tutorial.

**Comment by louis-md** [comment]
Thanks @valle-xyz for the feedback! 🙌 I implemented most changes. 

About the remaining ones:

> **Passkeys React Tutorial:**
> 
> * The light mode does not really work. 
>
> [...]
>
> **Passkey Vue:**
> 
> * The Safe Link and Jiffyscan Link do not work (I think the variables should be reactive)
> * [...]
> * On Chrome, only light mode works, so even when the browser is set to dark mode, the app displays light mode.

Hm I'd be happy to jump on a call on Monday to check this together! So I could replicate the bug. Note that the correct icons are in the `fix-light-theme` branch of the tutorials' repos.

> 
> **7579 tutorial:**
> 
> * is not functional, as multiple files have not been created.

We can sync on this too to know what are the missing files 👍

> * I think we should add versions to the packages to avoid breaking changes because packages change the API, and we cannot update our tutorials in time. This would have happened in this case, as permissionless.js had breaking changes.

We can discuss this with @tanay1337 as I see he removed the mentions to fixed versions in earlier commits.

🚀

**Review by valle-xyz — APPROVED** [review]

**Pull request merged**
