### PR TITLE
Refactor: Update Open Coinverse Guide to Safe open info

### PR DESCRIPTION
**Pull request by adam-hurwitz**
- Convert Google doc to Markdown
- Refactor from 1 long page into topic-based pages organized by categories: About, Use, Compatibility, and Security
- Update links from Gnosis to Safe scheme
- Create a separate temporary GitHub repository for the Safe open info Markdown files: To incrementally merge into the main Safe docs where it makes sense to

### CODE REVIEW

**Comment by adam-hurwitz** [comment]
This is an updated pull request from the original [#168](https://github.com/safe-global/safe-docs/pull/168) that resolves merge conflicts and adds a link to the GitHub repository for contributions.

**Comment by ademidun** [comment]
Looks like it's giving 500 errors?


https://github.com/adam-hurwitz/safe-oi

Screen Shot 2023-03-24 at 10 21 56 AM

**Comment by ademidun** [comment]
A temporary issue I guess. It's working now! 🙌 

Screen Shot 2023-03-24 at 10 24 06 AM

**Review by ademidun — APPROVED** [review]
Thanks for doing this Adam! 🙌

**Pull request merged**
