### PR TITLE
Generate API reference

### PR DESCRIPTION
**Pull request by louis-md**

### CODE REVIEW

**Review by germartinez — CHANGES_REQUESTED** [review]
Feedback: https://5afe.slack.com/archives/C061LNH7A3Z/p1712840738765609?thread_ts=1712840474.293859&cid=C061LNH7A3Z

**Review by tanay1337 — CHANGES_REQUESTED** [review]
Shared some feedback here: https://5afe.slack.com/archives/C061LNH7A3Z/p1713174149691739?thread_ts=1712840474.293859&cid=C061LNH7A3Z

**Comment by louis-md** [comment]
Just pushed some changes:

A. Sidebar

~~A1. The sidebar should have similar styling (placement in the page, font, size, top margin, etc) as the rest of the pages for consistency.~~  :white_check_mark:
~~A2. We should add a Go to Advanced item on top of the sidebar (like in the SDK and Advanced sections).~~ :white_check_mark:
A3. The sidebar route titles should be descriptive as in the current format they get cut off.

B. Main page

~~B1. The base URL should be click to copy or should have a copy button next to it.~~ :white_check_mark:
B2. We should show a CURL and sample JS usage for each endpoint.
B3. We should show the sample responses for the endpoints. (Should discuss how to best handle this - custom from us or with the infra team adding it to the swagger spec).
B4. The page should be responsive.
B5. We should copy the formatting scheme (font size, colours, tables, etc) from Medusa - it’s easier to read with the design.
~~B6. The endpoints on the right should display only the /v1/… as it’s hard to read right now. Fair to copy the whole URL with the copy button though.~~ :white_check_mark:
B7. Subtitles should be improved and descriptive. Think it also related to A3.

~~C. General~~

~~C1. HTTP verbs should be all caps.~~ :white_check_mark:

**Review by tanay1337 — APPROVED** [review]
Super cool, @louis-md! Thanks 🙌

**Pull request merged**
